# Generated by Django 4.2.3 on 2023-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя')),
                ('position', models.CharField(db_index=True, max_length=150, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('name', 'position'),
            },
        ),
    ]
