# Generated by Django 4.2.3 on 2023-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя')),
                ('position', models.CharField(db_index=True, max_length=150, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, upload_to='static/images/team')),
                ('urls_facebook', models.CharField(db_index=True, max_length=150, verbose_name='Профиль Facebook')),
                ('urls_telegram', models.CharField(db_index=True, max_length=150, verbose_name='Профиль Телеграм')),
                ('urls_linkedn', models.CharField(db_index=True, max_length=150, verbose_name='Профиль Линкедин')),
                ('urls_instagram', models.CharField(db_index=True, max_length=150, verbose_name='Профиль Инстаграма')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'человека',
                'ordering': ('name', 'position'),
            },
        ),
    ]
