# Generated by Django 4.2.3 on 2023-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_urls_linkedn_team_urls_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150, verbose_name='Название пакета')),
                ('package_price', models.CharField(max_length=150, verbose_name='Цена')),
            ],
        ),
    ]
